# yamllint disable
---
- job:
    name: gitcontrol-test-integration
    parent: ansible-collection-test-integration
    description: |
      Execute ansible-test integration for the collection
    vars:
      ansible_test_test_command: "integration"
      ansible_test_no_temp_unicode: true
    files:
      - ^plugins/module_utils/git.py
      - ^plugins/module_utils/github.py
      - ^plugins/modules/github*
      - ^tests/integration/targets/github*
    pre-run: tests/playbooks/pre.yaml
    secrets:
      - secret: gitcontrol-secret
        name: gitcontrol

- secret:
    name: gitcontrol-secret
    data:
      github_token: !encrypted/pkcs1-oaep
        - QduY2mJaxznljZMLGoGE/LcHwb0Fk4QRcqX8DY+a8i320Rl0GdRE9yfFwkxfdFQ245UXT
          ZgcnHsuofTCbRQOWkt5eEN/+OqKqgvtDyP2QmOfOksbTUhnpWR1jV9/wDgqXIKTH7USgf
          EQbnaSBYCgUTIi2BZVhJBPEtb9AvO8h1NcrhCxR4R8Cw8PJ/bOzPAgfvZ/D9067S9smgz
          cKZyOuloBhwVRskdbj5tbvViya44cGDs13j6Dpvv1C2tgdVctM/6iHwvXyOL2PtTu5LCP
          3OVxgZCWx3XPzgfUl+QwL5KZSaDmsU6b7v5lr89HcTDrVmu02El6sEkMbUPQ/dDB6/7LK
          fzMxCXz17bSWehIt1ASC+e+1jkfZKXHC5ss/6ebzRESdEeYDMb/6ueq3FPNslRbKwoGTK
          54D8fSOIagjg+F+AYJjXaozslsj5S1Uv7HgGj6Ecgv75Hcx8/jJiUsqyHazx7EZ4CDBfG
          Lh28IR72f6JqALD01ontiYLWb7CdlxIa0zzNmmiA2oC/Zcvnef6hpSdvoFwmamY3HNUsM
          VsvUiEJiT0uRropSKEr4q3/uKbwsqqbQ8TkWj/CaKbZ+MeIR4N4WO54r81K8W7p/3W6pt
          qUFW1s/mMQWoYeQRh1gPHetpEgGfVP8d636Dk0hzK33vuvaJIfQdZxST7hkmuw=
      gitea_token: !encrypted/pkcs1-oaep
        - DdahPv/8fcUIVNPXPrraaXm8WKblT5IzMTH12fquGebo/IkGpuS0RSFJNjSvuPf959iwo
          PJGM3bpSXdlcHy+FTXDuIJDX8YEwSIUjDdTQlhJAVNz3sp5tN6a81SKb+dnTZVhR/JA9o
          klXdXFzrmZq/VdIPV1VDw9KdHzQmVhWhzJDSN2riIbbEDH0I64wymTN5p9ZnIMNH4yP3Y
          O+na+QG6HvpHPQvg1zH9SJ6zxgvqze+2AFMu+zKw0+F69eEYqyb/ZL5awynEI8uRQCgS8
          R67lDoNiz0zUQLRNxqLc1EPihID5C0u+vTTUi+d9AydBC3jqGufV0s11LyyOk36A0sogj
          Uol4aEvKZ46rgovbrd6KbNOXjB0pJTdqXLGr5ycLNEYO32EaboNrnx7ynkGZgtg7EN0fo
          pFoD0B9oqbW7XJpzRON+zlHZJYg0xVdjbK6jFCXAZEFfSpUUkKR/kdSjgXH4MktI9E1fd
          P6XNI9POSea8pj/Ct4GdCPYRUOVlS2uGKz2Wz+4zpL+c5WPjun3EY0J9RhpNERF13Iw8L
          YwntZI9IuP+6Dq7fZMnApcHkhMClgQIPW8UWEYwY+f4PFxYpcnnYSpJgLEo5Iu3pfQdgB
          c7K9L1tILzhcaLVZTpkf3tBzr6xZea97rGWQSs9LoQLSX9kqEgRPlh+T40VNjQ=
      gitea_api_url: !encrypted/pkcs1-oaep
        - PMruLkiJmaMG+d/+p966Ta5+FXtAFpqb/yG+2Ukm8p3OKWj4ldMXD8/lDWzZivK76fYJ1
          DlnMOJ9bBipb+WTFHVVWyZ9klLnBN//zaWHAvVht61I0fBKbRAvmGf0Fw5qtAn1Dp57bl
          FE9YptJJeXBfqZwMuaVjT2W2biweebJSpLXUoKsh0sEaTs0lrT6i6pc0DvJGJTRWL1IxP
          G5uSRy1HapqJxRLpxsytL6eHQV6cxDrtMIvLgRlPEVLsv4+vAP2QtjiQctuXHlr8ikl5s
          CkywZS3h9ia7KxmIJvT/oAyg38sQgFKE9m5+AG6F5253GdM9raa9NiinkaoSP3NkZjozc
          urdr/ai0azHgaGWytN6Q192uU6udRGQ2yIGfT4PJOijlIyX01TuclGp+LLbhaz40x8OEv
          BCvgvgR+Khi1iBx5ua5UuX/RNJwrVtzn0+AkjCu0G4k4RiCDAS5+eY9GfkG6gmCmR6zBU
          d19zv3zIvyVhx4cHvuXrx9uP9gyDSdD8ANMEq469JsFYJ6aaL7Q5n79u7F4QDkba93nix
          QrV8pdmfAa1E43jc+Iz32b724c45JMYQyUAcnbcIxBw/PNH2g6sZbBMrJmeRfCl6vmXgk
          CRFzNkNszOLwhfTCeuL1hB1xunOwGjC3sFZ7gq8Y2MW7lbivT+U+XH952w2acs=

- project:
    merge-mode: squash-merge
    vars:
      ansible_collection_namespace: "opentelekomcloud"
      ansible_collection_name: "gitcontrol"
    check:
      jobs:
        - otc-tox-pep8
        - otc-tox-linters
        - ansible-collection-test-sanity
        - ansible-collection-build
        - ansible-collection-docs
    check-post:
      jobs:
        - gitcontrol-test-integration
    gate:
      jobs:
        - otc-tox-pep8
        - otc-tox-linters
        - ansible-collection-test-sanity
        - ansible-collection-build
        - ansible-collection-docs
        - gitcontrol-test-integration
    release:
      jobs:
        - release-ansible-collection
    promote:
      jobs:
        - promote-ansible-collection-docs
